# Generated by Django 6.0.7 on 2026-07-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='disponibilidad',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('NO_DISPONIBLE', 'No disponible')], default='DISPONIBLE', help_text='Estado de disponibilidad visible para los clientes', max_length=20),
        ),
    ]
