# Generated by Django 6.0.7 on 2026-08-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_barbero_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='codigo_reserva',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
