# Generated by Django 6.0.7 on 2026-08-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_cita_codigo_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
